services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gtd-etl:
    build:
      context: .
      dockerfile: gtd-etl.dockerfile
    container_name: gtd-etl
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/
      DATABASE_NAME: gtd_database
      COLLECTION_NAME: incidents
    command: [ "python", "/gtd-etl/main.py" ]
    volumes:
      - ./MD003-E4:/gtd-etl

volumes:
  mongo_data:
